-- MySQL Script generated by MySQL Workbench
-- qui 12 mai 2022 15:04:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Presidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Presidente` (
  `idPresidente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `tempoDeMej` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idPresidente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diretor` (
  `idDiretor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `tempoDeMej` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NOT NULL,
  `Presidente_idPresidente` INT NOT NULL,
  PRIMARY KEY (`idDiretor`),
  INDEX `fk_Diretor_Presidente_idx` (`Presidente_idPresidente` ASC) VISIBLE,
  CONSTRAINT `fk_Diretor_Presidente`
    FOREIGN KEY (`Presidente_idPresidente`)
    REFERENCES `mydb`.`Presidente` (`idPresidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nucleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nucleo` (
  `sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membro` (
  `idMembro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `tempoDeMej` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `Diretor_idDiretor` INT NOT NULL,
  `Nucleo_sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idMembro`, `Nucleo_sigla`),
  INDEX `fk_Membro_Diretor1_idx` (`Diretor_idDiretor` ASC) VISIBLE,
  INDEX `fk_Membro_Nucleo1_idx` (`Nucleo_sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Membro_Diretor1`
    FOREIGN KEY (`Diretor_idDiretor`)
    REFERENCES `mydb`.`Diretor` (`idDiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membro_Nucleo1`
    FOREIGN KEY (`Nucleo_sigla`)
    REFERENCES `mydb`.`Nucleo` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFinal` DATE NULL,
  `finalizado` BIT NOT NULL,
  `Nucleo_sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idProjeto`, `Nucleo_sigla`),
  INDEX `fk_Projeto_Nucleo1_idx` (`Nucleo_sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Nucleo1`
    FOREIGN KEY (`Nucleo_sigla`)
    REFERENCES `mydb`.`Nucleo` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Membro_has_Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membro_has_Projeto` (
  `Membro_idMembro` INT NOT NULL,
  `Projeto_idProjeto` INT NOT NULL,
  PRIMARY KEY (`Membro_idMembro`, `Projeto_idProjeto`),
  INDEX `fk_Membro_has_Projeto_Projeto1_idx` (`Projeto_idProjeto` ASC) VISIBLE,
  INDEX `fk_Membro_has_Projeto_Membro1_idx` (`Membro_idMembro` ASC) VISIBLE,
  CONSTRAINT `fk_Membro_has_Projeto_Membro1`
    FOREIGN KEY (`Membro_idMembro`)
    REFERENCES `mydb`.`Membro` (`idMembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membro_has_Projeto_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `mydb`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
